### ISSUE TITLE
Build error:Unknown processor

### ISSUE THREAD

**Issue by Mfweb** [mcauser/BLUE_BUTTON_F103RET6#1]
I use that:
https://github.com/mcauser/micropython/tree/stm32f103
`make BOARD=BLUE_BUTTON_F103RET6`
```

system_stm32.c:143:2: error: #error Unknown processor
 #error Unknown processor
  ^~~~~
dma.c:63:6: error: #error "Unsupported Processor"
     #error "Unsupported Processor"

```

How can I modify the code?

**Comment by mcauser** [comment]
https://github.com/mcauser/micropython/blob/stm32f103/ports/stm32/system_stm32.c#L143

There's a whole bunch of places in the code that is yet to support STM32F1.

First pass looking for STM32F4 if statements and adding placeholders for STM32F1:
https://github.com/mcauser/micropython/commit/ad4bf9c646771cb68e0aae342a315448a67ce3cb

My branch is a few months old now and a few hundred commits behind master.
Not sure how far STM32F1 has progressed upstream.
